# https://taskfile.dev

version: '3'

tasks:
  lint:
    desc: Lint profile.d
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-lint.ps1

  validate:
    desc: Validate profile (lint + idempotency)
    cmds:
      - pwsh -NoProfile -File scripts/checks/validate-profile.ps1

  check-comment-help:
    desc: Check comment-based help
    cmds:
      - pwsh -NoProfile -File scripts/checks/check-comment-help.ps1

  test:
    desc: Run Pester Tests
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1

  test-unit:
    desc: Run Unit Test Suite
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Suite Unit

  test-integration:
    desc: Run Integration Test Suite
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Suite Integration

  test-performance:
    desc: Run Performance Test Suite
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Suite Performance

  test-coverage:
    desc: Run Pester Tests with Coverage
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Coverage

  benchmark:
    desc: Run Performance Benchmark
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/benchmark-startup.ps1

  security-scan:
    desc: Run Security Scan
    cmds:
      - pwsh -NoProfile -File scripts/utils/security/run-security-scan.ps1

  check-module-updates:
    desc: Check Module Updates
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/check-module-updates.ps1

  install-module-updates:
    desc: Install Module Updates
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/check-module-updates.ps1 -Update

  generate-changelog:
    desc: Generate Changelog
    cmds:
      - pwsh -NoProfile -File scripts/utils/docs/generate-changelog.ps1

  create-release:
    desc: Create Release (Dry Run)
    cmds:
      - pwsh -NoProfile -File scripts/utils/release/create-release.ps1 -DryRun

  generate-docs:
    desc: Generate API Documentation
    cmds:
      - pwsh -NoProfile -File scripts/utils/docs/generate-docs.ps1

  spellcheck:
    desc: Run Spellcheck
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/spellcheck.ps1

  markdownlint:
    desc: Run Markdownlint
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-markdownlint.ps1

  install-githooks:
    desc: Install Git hooks
    cmds:
      - pwsh -NoProfile -File scripts/git/install-githooks.ps1

  format:
    desc: Format Code
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-format.ps1

  find-duplicates:
    desc: Find Duplicate Functions
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/find-duplicate-functions.ps1

  generate-fragment-readmes:
    desc: Generate Fragment READMEs
    cmds:
      - pwsh -NoProfile -File scripts/utils/docs/generate-fragment-readmes.ps1

  check-commit-messages:
    desc: Check Commit Messages
    cmds:
      - pwsh -NoProfile -File scripts/checks/check-commit-messages.ps1

  update-baseline:
    desc: Update Performance Baseline
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/benchmark-startup.ps1 -UpdateBaseline

  quality-check:
    desc: Full Quality Check (format + security + lint + spellcheck + markdownlint + help + tests + function naming)
    deps: [format, security-scan, lint, spellcheck, markdownlint, check-comment-help, test, validate-function-naming]
    cmds:
      - echo "All quality checks passed"

  pre-commit-checks:
    desc: Run Pre-commit Checks
    cmds:
      - pwsh -NoProfile -File scripts/git/pre-commit.ps1

  check-idempotency:
    desc: Check Idempotency
    cmds:
      - pwsh -NoProfile -File scripts/checks/check-idempotency.ps1

  validate-function-naming:
    desc: Validate Function Naming Conventions
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/validate-function-naming.ps1

  validate-dependencies:
    desc: Validate Dependencies
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/validate-dependencies.ps1

  check-vulnerabilities:
    desc: Check Dependency Updates (Vulnerability scanning can be added)
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/check-module-updates.ps1

  format-and-lint:
    desc: Format and Lint Code
    deps: [format, lint]
    cmds:
      - echo "Format and lint completed"

  all-docs:
    desc: Generate All Documentation (API docs + fragment READMEs)
    deps: [generate-docs, generate-fragment-readmes]
    cmds:
      - echo "All documentation generated"

  default:
    desc: Run default task
    cmds:
      - task --list-all
