# https://taskfile.dev

version: '3'

tasks:
  lint:
    desc: Lint profile.d
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-lint.ps1

  validate:
    desc: Validate profile (lint + idempotency)
    cmds:
      - pwsh -NoProfile -File scripts/checks/validate-profile.ps1

  check-comment-help:
    desc: Check comment-based help
    cmds:
      - pwsh -NoProfile -File scripts/checks/check-comment-help.ps1

  test:
    desc: Run Pester Tests
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Coverage -Parallel {{.CLI_ARGS}}

  test-unit:
    desc: Run Unit Test Suite
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Suite Unit -Parallel {{.CLI_ARGS}}

  test-integration:
    desc: Run Integration Test Suite
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Suite Integration -Parallel {{.CLI_ARGS}}

  test-performance:
    desc: Run Performance Test Suite
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Suite Performance -Parallel {{.CLI_ARGS}}

  test-coverage:
    desc: Run Pester Tests with Coverage
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-pester.ps1 -Coverage -Parallel {{.CLI_ARGS}}

  benchmark:
    desc: Run Performance Benchmark
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/benchmark-startup.ps1

  security-scan:
    desc: Run Security Scan
    cmds:
      - pwsh -NoProfile -File scripts/utils/security/run-security-scan.ps1

  diagnose-profile-performance:
    desc: Diagnose profile performance issues
    cmds:
      - pwsh -NoProfile -File scripts/utils/performance/diagnose-profile-performance.ps1

  optimize-git-performance:
    desc: Optimize Git performance
    cmds:
      - pwsh -NoProfile -File scripts/utils/performance/optimize-git-performance.ps1 {{.CLI_ARGS}}

  check-module-updates:
    desc: Check Module Updates
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/check-module-updates.ps1 {{.CLI_ARGS}}

  install-module-updates:
    desc: Install Module Updates
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/check-module-updates.ps1 -Update {{.CLI_ARGS}}

  generate-changelog:
    desc: Generate Changelog
    cmds:
      - pwsh -NoProfile -File scripts/utils/docs/generate-changelog.ps1 {{.CLI_ARGS}}

  generate-dashboard:
    desc: Generate metrics dashboard
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/generate-dashboard.ps1 {{.CLI_ARGS}}

  create-release:
    desc: Create Release (Dry Run)
    cmds:
      - pwsh -NoProfile -File scripts/utils/release/create-release.ps1 -DryRun

  generate-docs:
    desc: Generate API Documentation
    cmds:
      - pwsh -NoProfile -File scripts/utils/docs/generate-docs.ps1 {{.CLI_ARGS}}

  spellcheck:
    desc: Run Spellcheck
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/spellcheck.ps1

  db-health:
    desc: Check health of all SQLite databases
    cmds:
      - pwsh -NoProfile -File scripts/utils/database/database-maintenance.ps1 -Action health

  db-statistics:
    desc: Get statistics for all SQLite databases
    cmds:
      - pwsh -NoProfile -File scripts/utils/database/database-maintenance.ps1 -Action statistics

  db-optimize:
    desc: Optimize all SQLite databases
    cmds:
      - pwsh -NoProfile -File scripts/utils/database/database-maintenance.ps1 -Action optimize

  db-backup:
    desc: Backup all SQLite databases
    cmds:
      - pwsh -NoProfile -File scripts/utils/database/database-maintenance.ps1 -Action backup

  db-repair:
    desc: Repair corrupted SQLite databases
    cmds:
      - pwsh -NoProfile -File scripts/utils/database/database-maintenance.ps1 -Action repair

  db-validate:
    desc: Validate SQLite database implementation and configuration
    cmds:
      - pwsh -NoProfile -File scripts/utils/database/validate-databases.ps1

  db-validate-full:
    desc: Validate SQLite databases with operation testing
    cmds:
      - pwsh -NoProfile -File scripts/utils/database/validate-databases.ps1 -TestOperations

  db-init:
    desc: Initialize all SQLite databases
    cmds:
      - pwsh -NoProfile -File scripts/utils/database/initialize-databases.ps1

  clear-fragment-cache:
    desc: Clear fragment cache (in-memory and SQLite database)
    cmds:
      - pwsh -NoProfile -File scripts/utils/clear-fragment-cache.ps1 {{.CLI_ARGS}}

  build-fragment-cache:
    desc: Build/warm fragment cache by parsing all fragments
    cmds:
      - pwsh -NoProfile -File scripts/utils/build-fragment-cache.ps1 {{.CLI_ARGS}}

  validate-fragment-cache:
    desc: Validate fragment cache (verify cache state)
    cmds:
      - pwsh -NoProfile -File scripts/utils/verify-cache-cleared.ps1 {{.CLI_ARGS}}

  check-script-standards:
    desc: Check script standards and best practices
    cmds:
      - pwsh -NoProfile -File scripts/checks/check-script-standards.ps1

  markdownlint:
    desc: Run Markdownlint
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-markdownlint.ps1

  install-githooks:
    desc: Install Git hooks
    cmds:
      - pwsh -NoProfile -File scripts/git/install-githooks.ps1 {{.CLI_ARGS}}

  install-pre-commit-hook:
    desc: Install pre-commit hook only
    cmds:
      - pwsh -NoProfile -File scripts/git/install-pre-commit-hook.ps1

  format:
    desc: Format Code
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/run-format.ps1 {{.CLI_ARGS}}

  find-duplicates:
    desc: Find Duplicate Functions
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/find-duplicate-functions.ps1

  generate-fragment-readmes:
    desc: Generate Fragment READMEs
    cmds:
      - pwsh -NoProfile -File scripts/utils/docs/generate-fragment-readmes.ps1 {{.CLI_ARGS}}

  new-fragment:
    desc: Create a new profile fragment from template
    cmds:
      - pwsh -NoProfile -File scripts/utils/fragment/new-fragment.ps1 {{.CLI_ARGS}}

  generate-command-wrappers:
    desc: Generate standalone script wrappers for fragment commands
    cmds:
      - pwsh -NoProfile -File scripts/utils/fragment/generate-command-wrappers.ps1 {{.CLI_ARGS}}

  check-commit-messages:
    desc: Check Commit Messages
    cmds:
      - pwsh -NoProfile -File scripts/checks/check-commit-messages.ps1

  update-baseline:
    desc: Update Performance Baseline
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/benchmark-startup.ps1 -UpdateBaseline {{.CLI_ARGS}}

  collect-code-metrics:
    desc: Collect code metrics
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/collect-code-metrics.ps1

  export-metrics:
    desc: Export metrics data
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/export-metrics.ps1

  save-metrics-snapshot:
    desc: Save a metrics snapshot
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/save-metrics-snapshot.ps1

  track-coverage-trends:
    desc: Track test coverage trends over time
    cmds:
      - pwsh -NoProfile -File scripts/utils/metrics/track-coverage-trends.ps1

  quality-check:
    desc: Full Quality Check (format + security + lint + spellcheck + markdownlint + help + tests + function naming)
    deps: [format, security-scan, lint, spellcheck, markdownlint, check-comment-help, test, validate-function-naming]
    cmds:
      - echo "All quality checks passed"

  pre-commit-checks:
    desc: Run Pre-commit Checks
    cmds:
      - pwsh -NoProfile -File scripts/git/pre-commit.ps1

  check-idempotency:
    desc: Check Idempotency
    cmds:
      - pwsh -NoProfile -File scripts/checks/check-idempotency.ps1

  validate-function-naming:
    desc: Validate Function Naming Conventions
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/validate-function-naming.ps1

  check-missing-tests:
    desc: Check for Missing Tests
    cmds:
      - pwsh -NoProfile -File scripts/utils/code-quality/check-missing-tests.ps1

  validate-dependencies:
    desc: Validate Dependencies
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/validate-dependencies.ps1

  check-missing-packages:
    desc: Check for missing packages and modules
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/check-missing-packages.ps1

  check-vulnerabilities:
    desc: Check Dependency Updates (Vulnerability scanning can be added)
    cmds:
      - pwsh -NoProfile -File scripts/utils/dependencies/check-module-updates.ps1

  format-and-lint:
    desc: Format and Lint Code
    deps: [format, lint]
    cmds:
      - echo "Format and lint completed"

  all-docs:
    desc: Generate All Documentation (API docs + fragment READMEs)
    deps: [generate-docs, generate-fragment-readmes]
    cmds:
      - echo "All documentation generated"

  init-wrangler-config:
    desc: Initialize wrangler configuration
    cmds:
      - pwsh -NoProfile -File scripts/utils/setup/init-wrangler-config.ps1 {{.CLI_ARGS}}

  dev-setup:
    desc: Run development environment setup
    cmds:
      - pwsh -NoProfile -File scripts/dev/setup.ps1

  check-task-parity:
    desc: Check task parity across all task runner files
    cmds:
      - pwsh -NoProfile -File scripts/utils/task-parity/check-task-parity.ps1 {{.CLI_ARGS}}

  generate-task-parity:
    desc: Generate missing tasks to achieve parity across all task runner files
    cmds:
      - pwsh -NoProfile -File scripts/utils/task-parity/check-task-parity.ps1 -Generate {{.CLI_ARGS}}

  default:
    desc: Run default task
    cmds:
      - task --list-all
